language: minimal
#addons:
#  apt:
#    packages:
#    - realpath
arch:
  - arm64
os:
  - linux
services:
  - docker

before_install:
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
script: 
  - cd percona-server-8.0
  - docker build . -f Dockerfile -t toyangdon/percona:8.0
  - docker push toyangdon/percona:8.0
